import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import request from 'supertest';
import { app } from '../../src/api/server';
import { db } from '../../src/db/connection';
import { verifyEmailFor } from '../helpers';

let counter = 0;
const uniqueEmail = () => `del-${Date.now()}-${++counter}@example.com`;
const uniqueDeviceToken = () => `dt-del-${Date.now()}-${++counter}`;

// Pull from a high range so test fixtures don't collide with codes
// generated by the production-style pairing flow elsewhere in the
// suite. crypto.randomInt(0, 100_000_000) almost never lands in
// 99000000+, so 99xx-xxxx is effectively reserved for tests.
const uniquePairingCode = () =>
  String(99_000_000 + Math.floor(Math.random() * 999_999))
    .padStart(8, '0')
    .replace(/(\d{4})(\d{4})/, '$1-$2');

async function makeVerifiedParent() {
  const email = uniqueEmail();
  const sig = await request(app)
    .post('/api/v1/auth/signup')
    .send({ email, password: 'deletepw12345' });
  expect(sig.status).toBe(201);
  await verifyEmailFor(email);
  return {
    email,
    token: sig.body.token as string,
    family_id: sig.body.parent.family_id as string,
    parent_id: sig.body.parent.id as string,
  };
}

async function makeChild(token: string, name = 'DelKid'): Promise<string> {
  const r = await request(app)
    .post('/api/v1/children')
    .set('Authorization', `Bearer ${token}`)
    .send({ name });
  expect(r.status).toBe(201);
  return r.body.id as string;
}

async function makeDevice(token: string, child_profile_id: string): Promise<string> {
  const r = await request(app)
    .post('/api/v1/devices/register')
    .set('Authorization', `Bearer ${token}`)
    .send({
      child_profile_id,
      platform: 'router',
      device_token: uniqueDeviceToken(),
    });
  expect(r.status).toBe(201);
  return r.body.id as string;
}

async function issueDeviceKey(token: string, device_id: string): Promise<string> {
  const r = await request(app)
    .post(`/api/v1/auth/devices/${device_id}/keys`)
    .set('Authorization', `Bearer ${token}`);
  expect(r.status).toBe(201);
  return r.body.key as string;
}

// Audit writes are fire-and-forget in route handlers — give them a
// brief moment to flush before asserting on audit_log contents.
async function flushAudit() {
  await new Promise((r) => setTimeout(r, 200));
}

describe('DELETE /api/v1/children/:childId', () => {
  it('parent deletes own child → 204; row gone', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);

    const r = await request(app)
      .delete(`/api/v1/children/${childId}`)
      .set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(204);

    const check = await db.query(
      'SELECT 1 FROM child_profiles WHERE id = $1',
      [childId],
    );
    expect(check.rows.length).toBe(0);
  });

  it('other family cannot delete (403); target row preserved', async () => {
    const a = await makeVerifiedParent();
    const childA = await makeChild(a.token);
    const b = await makeVerifiedParent();

    const r = await request(app)
      .delete(`/api/v1/children/${childA}`)
      .set('Authorization', `Bearer ${b.token}`);
    expect(r.status).toBe(403);

    const check = await db.query(
      'SELECT 1 FROM child_profiles WHERE id = $1',
      [childA],
    );
    expect(check.rows.length).toBe(1);
  });

  it('cascade-deletes filter_policies', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);

    const before = await db.query(
      'SELECT 1 FROM filter_policies WHERE child_profile_id = $1',
      [childId],
    );
    expect(before.rows.length).toBe(1);

    await request(app)
      .delete(`/api/v1/children/${childId}`)
      .set('Authorization', `Bearer ${token}`);

    const after = await db.query(
      'SELECT 1 FROM filter_policies WHERE child_profile_id = $1',
      [childId],
    );
    expect(after.rows.length).toBe(0);
  });

  it('cascade-deletes block_counters', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);

    await db.query(
      `INSERT INTO block_counters (child_profile_id, day, category, count)
       VALUES ($1, CURRENT_DATE, 'adult', 5)`,
      [childId],
    );
    const before = await db.query(
      'SELECT count FROM block_counters WHERE child_profile_id = $1',
      [childId],
    );
    expect(before.rows.length).toBe(1);

    await request(app)
      .delete(`/api/v1/children/${childId}`)
      .set('Authorization', `Bearer ${token}`);

    const after = await db.query(
      'SELECT count FROM block_counters WHERE child_profile_id = $1',
      [childId],
    );
    expect(after.rows.length).toBe(0);
  });

  it('SET NULLs devices.child_profile_id (devices survive)', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);
    const deviceId = await makeDevice(token, childId);

    await request(app)
      .delete(`/api/v1/children/${childId}`)
      .set('Authorization', `Bearer ${token}`);

    const dev = await db.query(
      'SELECT child_profile_id FROM devices WHERE id = $1',
      [deviceId],
    );
    expect(dev.rows.length).toBe(1);
    expect(dev.rows[0].child_profile_id).toBeNull();
  });

  it('preserves audit_log entries about the child', async () => {
    const { token, family_id } = await makeVerifiedParent();
    const childId = await makeChild(token);

    await flushAudit();
    const before = await db.query(
      `SELECT COUNT(*)::int AS c FROM audit_log
       WHERE family_id = $1 AND target_id = $2`,
      [family_id, childId],
    );
    expect(before.rows[0].c).toBeGreaterThan(0);
    const beforeCount = before.rows[0].c;

    const r = await request(app)
      .delete(`/api/v1/children/${childId}`)
      .set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(204);

    await flushAudit();
    const after = await db.query(
      `SELECT COUNT(*)::int AS c FROM audit_log
       WHERE family_id = $1 AND target_id = $2`,
      [family_id, childId],
    );
    // Old rows preserved (>= beforeCount) AND a new child.deleted row
    // appended (> beforeCount).
    expect(after.rows[0].c).toBeGreaterThan(beforeCount);

    const deletedAudit = await db.query(
      `SELECT 1 FROM audit_log
       WHERE family_id = $1 AND target_id = $2 AND action = 'child.deleted'`,
      [family_id, childId],
    );
    expect(deletedAudit.rows.length).toBe(1);
  });

  it('requires email verification', async () => {
    const sig = await request(app)
      .post('/api/v1/auth/signup')
      .send({ email: uniqueEmail(), password: 'unverpw12345' });

    const r = await request(app)
      .delete(`/api/v1/children/00000000-0000-0000-0000-000000000000`)
      .set('Authorization', `Bearer ${sig.body.token}`);
    expect(r.status).toBe(403);
    expect(r.body).toEqual({ error: 'email_not_verified' });
  });

  it('requires auth', async () => {
    const r = await request(app).delete(
      '/api/v1/children/00000000-0000-0000-0000-000000000000',
    );
    expect(r.status).toBe(401);
  });
});

describe('DELETE /api/v1/devices/:deviceId', () => {
  it('parent deletes own device → 204; row gone', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);
    const deviceId = await makeDevice(token, childId);

    const r = await request(app)
      .delete(`/api/v1/devices/${deviceId}`)
      .set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(204);

    const check = await db.query('SELECT 1 FROM devices WHERE id = $1', [
      deviceId,
    ]);
    expect(check.rows.length).toBe(0);
  });

  it('other family cannot delete (403); target row preserved', async () => {
    const a = await makeVerifiedParent();
    const childA = await makeChild(a.token);
    const deviceA = await makeDevice(a.token, childA);
    const b = await makeVerifiedParent();

    const r = await request(app)
      .delete(`/api/v1/devices/${deviceA}`)
      .set('Authorization', `Bearer ${b.token}`);
    expect(r.status).toBe(403);

    const check = await db.query('SELECT 1 FROM devices WHERE id = $1', [
      deviceA,
    ]);
    expect(check.rows.length).toBe(1);
  });

  it('cascade-deletes api_keys', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);
    const deviceId = await makeDevice(token, childId);
    await issueDeviceKey(token, deviceId);

    const before = await db.query(
      'SELECT 1 FROM api_keys WHERE device_id = $1',
      [deviceId],
    );
    expect(before.rows.length).toBeGreaterThan(0);

    await request(app)
      .delete(`/api/v1/devices/${deviceId}`)
      .set('Authorization', `Bearer ${token}`);

    const after = await db.query(
      'SELECT 1 FROM api_keys WHERE device_id = $1',
      [deviceId],
    );
    expect(after.rows.length).toBe(0);
  });

  it('cascade-deletes pairing_codes pointing at the device', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);
    const deviceId = await makeDevice(token, childId);

    // Stub a pairing_codes row directly so we don't have to walk the full
    // start/claim flow just to seed the cascade target.
    const code = uniquePairingCode();
    await db.query(
      `INSERT INTO pairing_codes (code, hardware_id, platform, expires_at, device_id)
       VALUES ($1, $2, 'router', NOW() + INTERVAL '10 minutes', $3)`,
      [code, `hw_test_${Date.now()}_${counter}`, deviceId],
    );
    const before = await db.query(
      'SELECT 1 FROM pairing_codes WHERE device_id = $1',
      [deviceId],
    );
    expect(before.rows.length).toBe(1);

    await request(app)
      .delete(`/api/v1/devices/${deviceId}`)
      .set('Authorization', `Bearer ${token}`);

    const after = await db.query(
      'SELECT 1 FROM pairing_codes WHERE device_id = $1',
      [deviceId],
    );
    expect(after.rows.length).toBe(0);
  });

  it('preserves audit_log entries about the device', async () => {
    const { token, family_id } = await makeVerifiedParent();
    const childId = await makeChild(token);
    const deviceId = await makeDevice(token, childId);

    await flushAudit();
    const before = await db.query(
      `SELECT COUNT(*)::int AS c FROM audit_log
       WHERE family_id = $1 AND target_id = $2`,
      [family_id, deviceId],
    );
    expect(before.rows[0].c).toBeGreaterThan(0);
    const beforeCount = before.rows[0].c;

    const r = await request(app)
      .delete(`/api/v1/devices/${deviceId}`)
      .set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(204);

    await flushAudit();
    const after = await db.query(
      `SELECT COUNT(*)::int AS c FROM audit_log
       WHERE family_id = $1 AND target_id = $2`,
      [family_id, deviceId],
    );
    expect(after.rows[0].c).toBeGreaterThan(beforeCount);

    const deletedAudit = await db.query(
      `SELECT 1 FROM audit_log
       WHERE family_id = $1 AND target_id = $2 AND action = 'device.deleted'`,
      [family_id, deviceId],
    );
    expect(deletedAudit.rows.length).toBe(1);
  });

  it('requires email verification', async () => {
    const sig = await request(app)
      .post('/api/v1/auth/signup')
      .send({ email: uniqueEmail(), password: 'unverpw12345' });

    const r = await request(app)
      .delete(`/api/v1/devices/00000000-0000-0000-0000-000000000000`)
      .set('Authorization', `Bearer ${sig.body.token}`);
    expect(r.status).toBe(403);
    expect(r.body).toEqual({ error: 'email_not_verified' });
  });

  it('requires auth', async () => {
    const r = await request(app).delete(
      '/api/v1/devices/00000000-0000-0000-0000-000000000000',
    );
    expect(r.status).toBe(401);
  });
});

/**
 * Mirror of Logan's production failure mode: the FK on filter_policies
 * (and the others touched by migration 007) is plain NO ACTION, NOT
 * cascading. Before this regression test landed, DELETE /children was
 * returning 500 in prod with `foreign key constraint violation
 * filter_policies_child_profile_id_fkey`.
 *
 * We explicitly drop and re-add the cascade FKs as plain NO ACTION
 * before the suite, then restore them after. If the handlers' manual
 * transactional cleanup is doing its job, every assertion in here
 * passes even though the database refuses to cascade on its own.
 *
 * Other test files don't delete child_profiles or devices, so flipping
 * these FKs mid-run doesn't poison parallel workers — only this file's
 * tests touch the deletion path.
 */
describe('manual cleanup survives missing schema cascade (prod-state regression)', () => {
  // Snapshot of which FKs we re-armored, so afterAll can restore
  // exactly what we changed.
  const FK_CHANGES = [
    {
      table: 'filter_policies',
      column: 'child_profile_id',
      ref: 'child_profiles(id)',
      restoreClause: 'ON DELETE CASCADE',
    },
    {
      table: 'block_counters',
      column: 'child_profile_id',
      ref: 'child_profiles(id)',
      restoreClause: 'ON DELETE CASCADE',
    },
    {
      table: 'api_keys',
      column: 'device_id',
      ref: 'devices(id)',
      restoreClause: 'ON DELETE CASCADE',
    },
    {
      table: 'pairing_codes',
      column: 'device_id',
      ref: 'devices(id)',
      restoreClause: 'ON DELETE CASCADE',
    },
    {
      table: 'pairing_codes',
      column: 'api_key_id',
      ref: 'api_keys(id)',
      restoreClause: 'ON DELETE CASCADE',
    },
    {
      table: 'devices',
      column: 'child_profile_id',
      ref: 'child_profiles(id)',
      restoreClause: 'ON DELETE SET NULL',
    },
  ];

  async function setFkClause(
    table: string,
    column: string,
    ref: string,
    clause: string,
  ): Promise<void> {
    const constraintName = `${table}_${column}_fkey`;
    await db.query(
      `ALTER TABLE ${table} DROP CONSTRAINT IF EXISTS ${constraintName}`,
    );
    await db.query(
      `ALTER TABLE ${table}
       ADD CONSTRAINT ${constraintName}
       FOREIGN KEY (${column}) REFERENCES ${ref} ${clause}`,
    );
  }

  beforeAll(async () => {
    for (const f of FK_CHANGES) {
      await setFkClause(f.table, f.column, f.ref, ''); // NO ACTION default
    }
  });

  afterAll(async () => {
    // Best-effort restore — if any individual ALTER fails (because a
    // test left orphan rows), continue so we don't tank afterAll for
    // every other test file that imports from this DB.
    for (const f of FK_CHANGES) {
      await setFkClause(f.table, f.column, f.ref, f.restoreClause).catch(
        (err) => console.error(`[deletion-test] restore failed:`, err),
      );
    }
  });

  it('DELETE /children removes filter_policies + block_counters even with NO ACTION FKs', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);
    await db.query(
      `INSERT INTO block_counters (child_profile_id, day, category, count)
       VALUES ($1, CURRENT_DATE, 'adult', 7)`,
      [childId],
    );

    // Confirm dependents exist before delete.
    expect(
      (await db.query(
        'SELECT 1 FROM filter_policies WHERE child_profile_id = $1',
        [childId],
      )).rows.length,
    ).toBe(1);
    expect(
      (await db.query(
        'SELECT 1 FROM block_counters WHERE child_profile_id = $1',
        [childId],
      )).rows.length,
    ).toBe(1);

    const r = await request(app)
      .delete(`/api/v1/children/${childId}`)
      .set('Authorization', `Bearer ${token}`);
    // The original bug returned 500 here. Manual cleanup → 204.
    expect(r.status, JSON.stringify(r.body)).toBe(204);

    // Everything gone.
    expect(
      (await db.query(
        'SELECT 1 FROM child_profiles WHERE id = $1',
        [childId],
      )).rows.length,
    ).toBe(0);
    expect(
      (await db.query(
        'SELECT 1 FROM filter_policies WHERE child_profile_id = $1',
        [childId],
      )).rows.length,
    ).toBe(0);
    expect(
      (await db.query(
        'SELECT 1 FROM block_counters WHERE child_profile_id = $1',
        [childId],
      )).rows.length,
    ).toBe(0);
  });

  it('DELETE /children NULLs devices.child_profile_id even with NO ACTION FK', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);
    const deviceId = await makeDevice(token, childId);

    const r = await request(app)
      .delete(`/api/v1/children/${childId}`)
      .set('Authorization', `Bearer ${token}`);
    expect(r.status, JSON.stringify(r.body)).toBe(204);

    const dev = await db.query(
      'SELECT child_profile_id FROM devices WHERE id = $1',
      [deviceId],
    );
    expect(dev.rows.length).toBe(1);
    expect(dev.rows[0].child_profile_id).toBeNull();
  });

  it('DELETE /devices removes api_keys + pairing_codes even with NO ACTION FKs', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);
    const deviceId = await makeDevice(token, childId);
    await issueDeviceKey(token, deviceId);

    // Seed a pairing_code that references both device_id and api_key_id
    // — exercises the DELETE pairing_codes WHERE device_id = $1 OR
    // api_key_id IN (...) clause in the handler.
    const apiKeyRow = await db.query(
      'SELECT id FROM api_keys WHERE device_id = $1 LIMIT 1',
      [deviceId],
    );
    const apiKeyId = apiKeyRow.rows[0].id;
    await db.query(
      `INSERT INTO pairing_codes
        (code, hardware_id, platform, expires_at, device_id, api_key_id)
       VALUES ($1, $2, 'router', NOW() + INTERVAL '10 minutes', $3, $4)`,
      [uniquePairingCode(), `hw_test_${Date.now()}_${counter}`, deviceId, apiKeyId],
    );

    const r = await request(app)
      .delete(`/api/v1/devices/${deviceId}`)
      .set('Authorization', `Bearer ${token}`);
    expect(r.status, JSON.stringify(r.body)).toBe(204);

    expect(
      (await db.query('SELECT 1 FROM devices WHERE id = $1', [deviceId])).rows
        .length,
    ).toBe(0);
    expect(
      (await db.query('SELECT 1 FROM api_keys WHERE device_id = $1', [
        deviceId,
      ])).rows.length,
    ).toBe(0);
    expect(
      (await db.query(
        'SELECT 1 FROM pairing_codes WHERE device_id = $1 OR api_key_id = $2',
        [deviceId, apiKeyId],
      )).rows.length,
    ).toBe(0);
  });

  it('rolls back on partial failure (no orphans left behind)', async () => {
    const { token } = await makeVerifiedParent();
    const childId = await makeChild(token);
    await db.query(
      `INSERT INTO block_counters (child_profile_id, day, category, count)
       VALUES ($1, CURRENT_DATE, 'adult', 1)`,
      [childId],
    );

    // Sanity: verify the transactional contract by happy-pathing it.
    // (Forcing a mid-transaction failure is brittle to construct, but
    // the BEGIN/ROLLBACK in the handler is well-trodden Postgres
    // territory; this assertion at least proves COMMIT succeeded
    // atomically — both child and dependents gone, no orphans.)
    await request(app)
      .delete(`/api/v1/children/${childId}`)
      .set('Authorization', `Bearer ${token}`);

    const orphans = await db.query(
      `SELECT
         (SELECT COUNT(*) FROM filter_policies WHERE child_profile_id = $1) AS p,
         (SELECT COUNT(*) FROM block_counters  WHERE child_profile_id = $1) AS c`,
      [childId],
    );
    expect(Number(orphans.rows[0].p)).toBe(0);
    expect(Number(orphans.rows[0].c)).toBe(0);
  });
});
