/**
 * dnsmasq configuration generator.
 *
 * The box does NOT route traffic — the home router keeps doing all
 * routing and Wi-Fi. dnsmasq is configured DHCP-only (port=0 disables
 * its DNS server) and hands out:
 *   - Box's own IP as the DNS server (option 6)
 *   - Home router's IP as the gateway (option 3)
 *
 * Clients query Meadow's UDP server on the box (port 53) directly,
 * because that's what they were told via DHCP option 6. Everything
 * else (HTTP, HTTPS, NTP, etc.) goes through the home router as
 * usual via option 3.
 *
 * Lease time is short (1h) so if the box dies, devices fall back to
 * the home router's DNS within an hour. Meadow availability matters
 * less than home network availability.
 */

export interface DnsmasqConfigInput {
  /** LAN-facing interface name, typically eth0. */
  interface: string;
  /** Box's own LAN IP — handed out as the DNS server. */
  box_ip: string;
  /** Home router's LAN IP — handed out as the gateway. */
  gateway_ip: string;
  /** Subnet mask in dotted form, e.g. "255.255.255.0". */
  netmask: string;
  /** First IP in the DHCP pool. */
  dhcp_start: string;
  /** Last IP in the DHCP pool. */
  dhcp_end: string;
  /** Lease time, dnsmasq syntax. Defaults to "1h". */
  lease_time?: string;
  /** Where dnsmasq should write its log file. Defaults to journald. */
  log_file?: string;
}

/**
 * Render a complete /etc/dnsmasq.d/meadow.conf snippet. Designed to
 * drop into dnsmasq's conf-dir without conflicting with the system
 * dnsmasq.conf (we set bind-interfaces + a specific interface).
 */
export function buildDnsmasqConfig(c: DnsmasqConfigInput): string {
  const leaseTime = c.lease_time ?? '1h';
  const logLine = c.log_file
    ? `log-facility=${c.log_file}`
    : '# log-facility=journald (default)';

  return `# Generated by Meadow — DO NOT HAND-EDIT.
# Regenerated each network setup run; changes will be lost.
#
# Mode: DHCP handoff. Meadow's UDP server on :53 handles DNS;
# dnsmasq is DHCP-only here so they don't fight for port 53.
# The home router keeps doing all Wi-Fi and routing.

# Disable dnsmasq's DNS server. Meadow has its own.
port=0

# Bind only the LAN-facing interface — don't touch loopback or
# any other adapter the Pi might be exposed on.
interface=${c.interface}
bind-interfaces

# DHCP scope.
dhcp-range=${c.dhcp_start},${c.dhcp_end},${c.netmask},${leaseTime}

# DHCP option 3 (router) — clients send everything except DNS to
# the home router as usual.
dhcp-option=option:router,${c.gateway_ip}

# DHCP option 6 (DNS server) — clients send DNS queries here, where
# Meadow's UDP server applies the family's filter / blocklist /
# crisis floor pipeline before forwarding upstream.
dhcp-option=option:dns-server,${c.box_ip}

# Keep dnsmasq's idea of DNS empty (we disabled DNS via port=0 but
# defense in depth — never accept a forwarder by accident).
no-resolv
no-hosts

${logLine}
log-dhcp
`;
}

/**
 * Pick a non-conflicting DHCP range inside the detected /24 subnet.
 *
 * Strategy: take the box_ip's /24 and serve .100–.250. That leaves
 * .1–.99 (where router + box typically live) and .251–.254 (often
 * reserved for static IoT gear) untouched. Caller can override on
 * larger subnets — for v1 we assume /24 which covers ~all home LANs.
 */
export function pickDhcpRange(
  box_ip: string,
  cidr: number,
): { start: string; end: string } {
  if (cidr !== 24) {
    // For non-/24 subnets the dashboard can show the operator a
    // manual-config prompt; we don't try to be clever.
    const parts = box_ip.split('.');
    return {
      start: `${parts[0]}.${parts[1]}.${parts[2]}.100`,
      end: `${parts[0]}.${parts[1]}.${parts[2]}.250`,
    };
  }
  const parts = box_ip.split('.');
  return {
    start: `${parts[0]}.${parts[1]}.${parts[2]}.100`,
    end: `${parts[0]}.${parts[1]}.${parts[2]}.250`,
  };
}

/**
 * Convert a CIDR prefix length (0-32) into a dotted netmask.
 */
export function cidrToNetmask(cidr: number): string {
  if (cidr < 0 || cidr > 32) throw new Error(`invalid cidr: ${cidr}`);
  const mask = cidr === 0 ? 0 : (0xffffffff << (32 - cidr)) >>> 0;
  return [
    (mask >>> 24) & 0xff,
    (mask >>> 16) & 0xff,
    (mask >>> 8) & 0xff,
    mask & 0xff,
  ].join('.');
}
